using System.Diagnostics;

namespace MT.TacticWar.Core
{
    [DebuggerDisplay("({X}, {Y})")]
    public class Coordinates
    {
        public static Coordinates Empty = new Coordinates(-1, -1);

        public int X { get; set; }
        public int Y { get; set; }

        public Coordinates(int x, int y)
        {
            X = x;
            Y = y;
        }

        public Coordinates Copy()
        {
            return new Coordinates(X, Y);
        }

        public override string ToString()
        {
            return $"({X}, {Y})";
        }

        public bool Equals(Coordinates coord)
        {
            return Equals(coord.X, coord.Y);
        }

        public bool Equals(int x, int y)
        {
            return X == x && Y == y;
        }

        public override bool Equals(object obj)
        {
            return obj is Coordinates ? Equals(obj as Coordinates) : false;
        }

        public override int GetHashCode()
        {
            // generated by VS
            var hashCode = 1861411795;
            hashCode = hashCode * -1521134295 + X.GetHashCode();
            hashCode = hashCode * -1521134295 + Y.GetHashCode();
            return hashCode;
        }
    }
}
